intranet/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('wao.urls')),
    path('admin/', admin.site.urls),
]

wao/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    path('', views.IndexView.index, name='index'),
    path('user/', views.UserView.user, name='user'),
    path('user/<int:user_id>', views.UserView.user_profile),
    path('user/update/', views.UpdateUserView.update),
    path('user/change-password/', views.ChangeUserPasswordView.change_password, name='change_password'),

    path('register/', views.RegisterView.register, name="register"),
    path('register/user/', views.RegisterView.register_user, name="form_user"),
    path('register/company/', views.RegisterView.register_company, name="form_company"),
    path('login/', views.LoginView.login, name="login"),
    path('logout/', views.LogoutView.logout, name="logout"),

    path('events/', views.EventsView.events, name='events'),
    path('events/create_event/', views.CreateEventView.create_event, name='events/create_event'),
    path('events/all_events/', views.AllEventsView.all_events, name='events/all_events'),
    path('events/event_info/<int:event_id>', views.EventInfoView.event_info, name='events/event_info'),
    path('events/search_events/', views.SearchEventsView.search_events, name='events/search_events'),
    path('events/subscribe_events/<int:event_id>/<int:user_id>/', views.SubscribeEventsView.subscribe_events, name='events/subscribe_events'),
    path('events/unsubscribe_events/<int:event_id>/<int:user_id>/', views.SubscribeEventsView.unsubscribe_events, name='events/unsubscribe_events'),
    path('events/get_participants/<int:event_id>/', views.SubscribeEventsView.get_participants, name='events/get_participants'),
    path('error', views.error, name='error'),

    path('programs/', views.ProgramsView.programs, name='programs'),
    path('programs/create_program/', views.CreateProgramView.create_program, name='programs/create_program'),
    path('programs/all_programs/', views.AllProgramsView.all_programs, name='programs/all_programs'),
    path('programs/search_programs/', views.SearchProgramView.search_program, name='programs/search_program'),
    path('programs/subscribe_programs/', views.SubscribeProgramsView.subscribe_programs,
         name='programs/subscribe_programs'),

    path('yearbook/', views.YearbookView.yearbook, name='yearbook'),
    path('yearbook/search_user/', views.YearbookView.search_user, name='yearbook/search_user'),

    path('moderate_user/', views.ModerationView.moderate_user, name='moderate_user'),
    path('moderate_user/<int:user_id>', views.ModerationView.moderate_user, name='moderate_user'),
    path('moderate_event/', views.ModerationView.moderate_event, name='moderate_event'),
    path('moderate_event/<int:event_id>', views.ModerationView.moderate_event, name='moderate_event'),
]

wao/models/beneficiary.py
from django.db import models


class Beneficiary(models.Model):
    """
    # TODO: Ask for documentation (Call Alexandre)
    """

    # CHOICES

    # DATABASE FIELDS
    name = models.CharField(unique=True, max_length=300, verbose_name='Nom')

    # MANAGERS

    # META CLASS
    class Meta:
        verbose_name = "Beneficiaire"
        verbose_name_plural = "Beneficiaires"

    # TO STRING METHOD
    def __str__(self):
        return self.name

    # SAVE METHOD

    # ABSOLUTE URL METHOD

    # OTHER METHODS

wao/models/category.py
from django.db import models


class Category(models.Model):
    """"
    There are 3 categories of members:
        1. Adherent
        2. Active
        3. Proactive
    that will depend on the implication at We Are One.
    """

    # CHOICES

    # DATABASE FIELDS
    name = models.CharField(unique=True, max_length=300, verbose_name='Nom')

    # MANAGERS

    # META CLASS
    class Meta:
        verbose_name = 'Catégorie'
        verbose_name_plural = 'Catégories'

    # TO STRING METHOD

    # SAVE METHOD
    def __str__(self):
        return self.name

    # ABSOLUTE URL METHOD

    # OTHER METHODS

wao/models/company.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from .membership_type import MembershipType


def upload_to_name(instance, filename):
    return 'wao/static/wao/profile_pictures/' + filename  # A CHANGER EN 'static/wao/profile_pictures/' EN PROD !!!


class Company(models.Model):
    """
    # TODO: Create documentation for company model
    """

    # CHOICES
    PUBLIC_LIMITED_COMPANY = 'PLC'
    PRIVATE_COMPANY_LIMITED = 'LTD'
    LIMITED_LIABILITY_PARTNERSHIP = 'LLP'
    COMPANY_TYPE_CHOICES = (
        (PUBLIC_LIMITED_COMPANY, 'Public limited company'),
        (PRIVATE_COMPANY_LIMITED, 'Private company limited by shares'),
        (LIMITED_LIABILITY_PARTNERSHIP, 'Limited liability partnership'),
    )

    # DATABASE FIELDS
    type = models.CharField(max_length=4, choices=COMPANY_TYPE_CHOICES)
    name = models.CharField(max_length=300, blank=True, null=True)
    email = models.EmailField(unique=True)
    telephone = PhoneNumberField(blank=True, null=True)
    birthday = models.DateField('Date de naissance', blank=True, null=True)
    photo = models.FileField(upload_to=upload_to_name,
                             blank=True)
    address = models.CharField(max_length=500, blank=True, null=True)
    membership_type = models.ForeignKey(MembershipType, on_delete=models.CASCADE, blank=True, null=True)
    address_complement = models.CharField(max_length=500, blank=True, null=True)
    zip_code = models.IntegerField(blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    twitter_link = models.CharField(max_length=200, blank=True, null=True)
    facebook_link = models.CharField(max_length=200, blank=True, null=True)
    linkedin_link = models.CharField(max_length=200, blank=True, null=True)

    # MANAGERS

    # META CLASS
    class Meta:
        verbose_name = 'Entreprise'
        verbose_name_plural = 'Entreprises'

    # TO STRING METHOD
    def __str__(self):
        return self.name

    # SAVE METHOD

    # ABSOLUTE URL METHOD

    # OTHER METHODS

wao/models/membership_type.py
from django.db import models


class MembershipType(models.Model):
    """"
    There are different types according to which type of profile we are dealing with (individual or entreprise)
    There are connected via the plateforme HelloAsso.
    For individuals:
        1. Student
        2. Young Pro
        3. Experimented
        4. Senior
    For companies:
        5. Entrepreneur & Asso
        6. Start-up
        7. Enterprise
        8. Corporate
    """

    # CHOICES

    # DATABASE FIELDS
    name = models.CharField(unique=True, max_length=300, verbose_name='Nom')

    # company_cotisation = models.BooleanField(verbose_name='Pour les entreprises', blank=True)

    # MANAGERS

    # META CLASS
    class Meta:
        verbose_name = 'Cotisation utilisateur'
        verbose_name_plural = 'Types de cotisation utilisateurs'

    # TO STRING METHOD
    def __str__(self):
        return self.name

    # SAVE METHOD

    # ABSOLUTE URL METHOD

    # OTHER METHODS

wao/views.py
import datetime

from django.contrib import messages
from django.contrib.auth import login, authenticate, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.views import generic

from .forms import EventCreationForm, UserUpdateForm
from .forms import UserRegistrationForm, CompanyRegistrationForm
from .models import User, Event
from django.db.models import Q
import xlwt


def error(request, message="Bienvenue sur la page d'affichage d'erreurs !"):
    # This special view is called everytime there is an error to display it into the browser
    return render(request, 'wao/error.html', {'messages': request.messages, })


class IndexView(generic.ListView):
    template_name = 'wao/index.html'

    def index(request):
        """"
        Temporary solution while we do not construct the queryset method
        """

        # The next 5 events from today on
        events = Event.objects.filter(begin_date__gt=datetime.date.today(), validated=True).order_by("begin_date")[:5]

        return render(request, 'wao/index.html', context={'events': events})


class RegisterView:
    def register(request):
        return render(request, 'wao/register.html')

    def register_user(request):
        context = {}
        if request.POST:
            if 'user_registration' in request.POST:
                form = UserRegistrationForm(request.POST, request.FILES or None)
                if form.is_valid():
                    incomplete_user = form.save(commit=False)
                    incomplete_user.is_enterprise = False
                    incomplete_user.is_active = False
                    email = form.cleaned_data.get('email')
                    raw_password = form.cleaned_data.get('password1')
                    incomplete_user.save()
                    login(request, incomplete_user, backend='django.contrib.auth.backends.ModelBackend')
                    return redirect('login')
                else:
                    context['user_registration_form'] = form
        else:
            user_form = UserRegistrationForm()
            context['user_registration_form'] = user_form
        return render(request, 'wao/register_user.html', context)

    def register_company(request):
        context = {}
        if request.POST:
            if 'company_registration' in request.POST:
                form = CompanyRegistrationForm(request.POST)
                if form.is_valid():
                    user = form.save(commit=False)
                    membership_id = user.membership_type
                    print(membership_id)
                    user.is_enterprise = True
                    user.is_active = False
                    email = form.cleaned_data.get('email')
                    raw_password = form.cleaned_data.get('password1')
                    user.save()
                    login(request, incomplete_user, backend='django.contrib.auth.backends.ModelBackend')
                    return redirect('login')
        else:
            company_form = CompanyRegistrationForm()
            context['company_registration_form'] = company_form
        return render(request, 'wao/register_company.html', context)


class LoginView(generic.ListView):
    def login(request):
        if request.method == 'POST':
            email = request.POST['email']
            password = request.POST['password']
            queryset = User.objects.filter(email=email)
            if len(queryset) != 0:
                if queryset[0].is_active:
                    user = authenticate(email=email, password=password)
                    if user is not None:
                        login(request, user)
                        return redirect('index')
                    else:
                        request.messages.append({
                            "type": "warning",
                            "header": "Erreur liée au mot de passe",
                            "content": "Mot de passe incorrect"
                        })
                        return error(request)
                else:
                    print('inactive')
                    request.messages.append({
                        "type": "warning",
                        "header": "Erreur liée à votre compte",
                        "content": "Votre compte n'a pas encore été validée ou a été désactivé"
                    })
                    return error(request)

            else:
                request.messages.append({
                    "type": "warning",
                    "header": "Erreur liée à l'identifiant",
                    "content": "E-mail incorrect"
                })
                return error(request)
        else:
            return render(request, 'wao/login.html')


class LogoutView(generic.ListView):
    def logout(request):
        logout(request)
        return HttpResponseRedirect('/')


class EventsView(generic.ListView):
    template_name = 'wao/events.html'

    def events(request):
        """"
        Temporary solution while we do not construct the queryset method
        """
        return render(request, 'wao/events.html')


class CreateEventView(generic.ListView):
    template_name = 'wao/create_event.html'

    def create_event(request):
        context = {}
        if request.POST:
            if 'event_creation' in request.POST:
                form = EventCreationForm(request.POST, request.FILES or None)
                if form.is_valid():
                    event = form.save(commit=False)
                    event.owner = request.user
                    event.save()
                    return HttpResponseRedirect('/events/all_events')
                else:
                    context['event_creation_form'] = form
        else:
            event_form = EventCreationForm()
            context['event_creation_form'] = event_form
        return render(request, 'wao/create_event.html', context)


class AllEventsView(generic.ListView):
    template_name = 'wao/all_events.html'

    def all_events(request):
        """"
        Temporary solution while we do not construct the queryset method
        """
        events = Event.objects.filter(begin_date__gt=datetime.date.today()).order_by("begin_date")
        return render(request, 'wao/all_events.html', {'events': events})


class EventInfoView(generic.ListView):
    template_name = 'wao/event_info.html'

    def event_info(request, event_id):
        """"
        Temporary solution while we do not construct the queryset method
        """
        event = Event.objects.get(id=event_id)
        
        total = len(event.participants.all()) + event.capacity
        show_participate = True

        for participant in event.participants.all():
            if request.user == participant:
                show_participate = False

        return render(request, 'wao/event_info.html', {'event': event, 'show_participate': show_participate, 'total':total})


class SearchEventsView(generic.ListView):
    template_name = 'wao/search_events.html'

    def search_events(request):
        """"
        Temporary solution while we do not construct the queryset method
        """
        query = request.GET.get('q')
        searched_events = Event.objects.filter(
            Q(title__icontains=query) | Q(description__icontains=query) | Q(type__icontains=query)
        )

        return render(request, 'wao/all_events.html', {'events': searched_events})


class SubscribeEventsView(generic.ListView):
    template_name = 'wao/event_info.html'

    def subscribe_events(request, event_id, user_id):
        """"
        Temporary solution while we do not construct the queryset method
        """
        
        event = Event.objects.get(id=event_id)
        user = User.objects.get(id=user_id)
        event.participants.add(user)
        event.capacity = event.capacity -1
        event.save()

        total = len(event.participants.all()) + event.capacity
        show_participate = True
        
        for participant in event.participants.all():
            if request.user == participant:
                show_participate = False


        return HttpResponseRedirect('/events/event_info/'+ str(event.id))

    def unsubscribe_events(request, event_id, user_id):
        """"
        Temporary solution while we do not construct the queryset method
        """
        
        event = Event.objects.get(id=event_id)
        user = User.objects.get(id=user_id)
        event.participants.remove(user)
        event.capacity = event.capacity +1
        event.save()

        total = len(event.participants.all()) + event.capacity
        show_participate = True
        
        for participant in event.participants.all():
            if request.user == participant:
                show_participate = False


        return HttpResponseRedirect('/events/event_info/'+ str(event.id))
    
    def get_participants(request, event_id):
        
        response = HttpResponse(content_type='application/ms-excel')
        response['Content-Disposition'] = "attachment; filename=participants.xls"

        wb = xlwt.Workbook(encoding='utf-8')
        ws = wb.add_sheet('Participants')

        # Sheet header, first row
        row_num = 0

        font_style = xlwt.XFStyle()
        font_style.font.bold = True

        columns = ['Prénom', 'Nom', 'Email']

        for col_num in range(len(columns)):
            ws.write(row_num, col_num, columns[col_num], font_style)

        # Sheet body, remaining rows
        font_style = xlwt.XFStyle()

        event = Event.objects.get(id=event_id)
        rows = event.participants.all().values_list('first_name', 'last_name', 'email')
        
        for row in rows:
            row_num += 1
            for col_num in range(len(row)):
                ws.write(row_num, col_num, row[col_num], font_style)

        

wao/templates/wao/all_events.html
{% extends 'wao/layouts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Créer un évènement{% endblock title %} {% block mystylesheet %}
<link rel="stylesheet" type="text/css" href="{% static 'wao/css/all_events.css' %}">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{{ form.media }}
{% endblock mystylesheet %}

{% block content %}
<div class="yellow-header">
    <p class="text-center text-white header-text">Calendrier des événements</p>
    <div class="separated-div-wrapper">
        <div class="separators header"></div>
        <div class="separators header center-white"></div>
        <div class="separators header"></div>
    </div>
</div>

<div class="py-2 text-center">
    <form action="/events/search_events/" class="form-inline my-2 my-lg-0 text-center">
        <input name="q" class="form-control mr-sm-2 search-text" type="search" placeholder="Chercher un événement..."
            aria-label="Search">
        <button class="search-button-event" type="submit">Chercher</button>
    </form>
    {% for event in events %}
    {% if event.validated %}
    <div class="blog-card">
        <div class="meta">
            {% if event.photo == "" %}
            <div class="photo" style="background-image: url('../../static/wao/event_pictures/default-event-image.png')">
            </div>
            {% else %}
            {% with photo=event.photo.url|cut:"wao/static/wao/" %}
            <div class="photo" style="background-image: url('../../static/wao/{{ photo }}')">
            </div>
            {% endwith %}
            {% endif %}
        </div>
        <div class="description text-left">
            <h1>{{ event.title }}</h1>
            <h2>{{ event.begin_date|date:"j F o à G:i" }}</h2>
            <p class="text">{{ event.description|truncatechars:90 }}</p>
            <p class="read-more">
                <a href="/events/event_info/{{ event.id }}">Voir plus</a>
            </p>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>









{% endblock content %}

wao/templates/wao/change_password.html
{% extends 'wao/layouts/base.html' %}
{% load static %}

{% block title %}Changer le mot de passe{% endblock title %}

{% block mystylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'wao/css/index.css' %}">
{% endblock mystylesheet %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Save changes</button>
    </form>
{% endblock content %}

wao/templates/wao/event_info.html
{% extends 'wao/layouts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Créer un évènement{% endblock title %} {% block mystylesheet %}
<link rel="stylesheet" type="text/css" href="{% static 'wao/css/event_info.css' %}">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{{ form.media }}
{% endblock mystylesheet %}

{% block content %}
<div class="yellow-header">
    <p class="text-center text-white header-text">Détail de l'événement</p>
    <div class="separated-div-wrapper">
        <div class="separators header"></div>
        <div class="separators header center-white"></div>
        <div class="separators header"></div>
    </div>
</div>

<div class="rela-block container">
    <div class="rela-block profile-card">
        {% if event.photo == "" %}
        <div class="photo" style="background-image: url('../../static/wao/event_pictures/default-event-image.png')">
        </div>
        {% else %}
        {% with photo=event.photo.url|cut:"wao/static/wao/" %}
        <div class="photo" style="background-image: url('../../static/wao/{{ photo }}')">
        </div>
        {% endwith %}
        {% endif %}

        <div class="rela-block profile-name-container">
            <div class="rela-block user-name" id="user_name">{{ event.title }}</div>
            <div class="rela-block user-desc" id="user_description"><i class="fas fa-inbox"></i> {{ event.type }}
            </div>
            <div class="row">
                <div class="rela-block user-job" id="event_price"><i class="fas fa-tag"></i>
                    {{ event.price }} €
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-12 rela-block user-job" id="event_address"><i class="fas fa-map-pin"></i>
                    {{ event.address }}</div>
            </div>
        </div>

        <div class="rela-block profile-card-stats">
            <div class="floated profile-stat works" id="num_works">{{ event.begin_date|date:"j F o à G:i" }}<br>
            </div>
            <div class="floated profile-stat following" id="num_following">{{ event.end_date|date:"j F o à G:i" }}<br>
            </div>
            <div class="floated profile-stat followers" id="num_followers">
                {{ event.capacity }}/{{ total }}<br></div>
        </div>
        {% if event.capacity == 0 %}
        <div class="text-center">
            <button class="mx-4 button text-center">Cet événement est complet</button>
        </div>
        <br>
        {% elif show_participate %}
        <div class="text-center">
            <button class="mx-4 button text-center" type="submit"
                onclick="location.href='/events/subscribe_events/{{ event.id }}/{{ user.id }}'">Participer</button>
        </div>
        <br>
        {% endif %}
        {% if not show_participate %}
        <div class="text-center">
            <button class="mx-4 button text-center participant">Vous participez à cet événement</button>
        </div>
        <br>
        <div class="text-center">
            <button class="mx-4 button text-center unsubscribe"
                onclick="location.href='/events/unsubscribe_events/{{ event.id }}/{{ user.id }}'">Annuler la
                participation</button>
        </div>
        <br>
        {% endif %}


        {% if event.owner.id == user.id %}
        <div class="text-center">
            <button class="mx-4 button text-center participant" type="submit"
                onclick="location.href='/events/get_participants/{{ event.id }}'">Liste des participants</button>
        </div>
        {% endif %}
        <br>
    </div>
</div>



{% endblock content %}

wao/templates/wao/events.html
{% extends 'wao/layouts/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

{% block title %}Nos évènements{% endblock title %}

{% block mystylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'wao/css/index.css' %}">
{% endblock mystylesheet %}

{% block content %}
    <div class="yellow-header">
        <p class="text-center text-white header-text">Évènements</p>
        <div class="separated-div-wrapper">
            <div class="separators header"></div>
            <div class="separators header center-white"></div>
            <div class="separators header"></div>
        </div>

    </div>
    <div class="container text-center pt-2">
        <h4>C'est ici pour créer ton évènement We Are One ! </h4>
        <div class="container text-center py-4">

            <button type="button" class="mx-4 button" onclick="location.href='create_event/'">Créer un évènement
            </button>
        </div>
    </div>
    <div class="container text-center pt-2">
        <h4>Évènements à venir !</h4>
    </div>

    <div class="container text-center py-4">

        <button type="button" class="mx-4 button" onclick="location.href='subscribe_events/'">M'inscrire à un
            évènement
        </button>
    </div>


    <div class="container text-center pt-2">
        <h4>Pour voir tous les événements !</h4>
    </div>

    <div class="container text-center py-4">
        <button type="button" class="mx-4 button" onclick="location.href='all_events/'">Liste d'évènements</button>
    </div>

{% endblock content %}

wao/templates/wao/register.html
{% extends 'wao/layouts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}S'inscrire{% endblock title %}

{% block mystylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'wao/css/register.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    {{ form.media }}
{% endblock mystylesheet %}

{% block content %}
    <div class="yellow-header">
        <p class="text-center text-white header-text">S'inscrire</p>
        <div class="separated-div-wrapper">
            <div class="separators header"></div>
            <div class="separators header center-white"></div>
            <div class="separators header"></div>
        </div>
    </div>


    <div class="container py-2">
        <p class="text-center"> Je suis :
            <a href="{% url 'form_user' %}">
                <button class="mx-4 button" type="button">
                    Un utilisateur
                </button>
            </a>
        </p>
    </div>
{% endblock content %}
{% block myjssheet %}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#id_birthday").datepicker();
        });
    </script>
{% endblock myjssheet %}

wao/templates/wao/register_user.html
{% extends 'wao/layouts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}S'inscrire{% endblock title %}

{% block mystylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'wao/css/register.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    {{ form.media }}
{% endblock mystylesheet %}

{% block content %}
    <div class="yellow-header">
        <p class="text-center text-white header-text">S'inscrire</p>
        <div class="separated-div-wrapper">
            <div class="separators header"></div>
            <div class="separators header center-white"></div>
            <div class="separators header"></div>
        </div>
    </div>


    <div class="container py-2">
        <div id="userForm">
            <div class="card card-body">
                Les champs suivis d'une astérisque sont obligatoires. <br>
                <form method="POST" enctype='multipart/form-data'>
                    {% csrf_token %}
                    {% for field in user_registration_form %}
                        <p>
                            {{ field | as_crispy_field }}
                            {% for error in field.errors %}
                                <small class="errors">{{ error }}</small>
                            {% endfor %}
                        </p>
                    {% endfor %}
                    <button class="btn btn-primary" type="submit" name="user_registration">S'inscrire</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

{% block myjssheet %}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#id_birthday").datepicker();
        });
    </script>
{% endblock myjssheet %}

wao/templates/wao/search_events.html
{% extends 'wao/layouts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Rechercher un évènement{% endblock title %}

{% block mystylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'wao/css/index.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    {{ form.media }}
{% endblock mystylesheet %}

{% block content %}
    <div class="container-fluid text-center pt-2 tracking-in-contract-bck">
        <h1>Rechercher un évènement</h1>
    </div>
{% endblock content %}

wao/templates/wao/update.html
{% extends 'wao/layouts/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Éditer mes informations{% endblock title %}

{% block mystylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'wao/css/register.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    {{ form.media }}
{% endblock mystylesheet %}

{% block content %}
    {#TODO: Check if the user is logged, if not show an error message ! Otherwise, proceed to the update page (user, company)#}

    {% if user.is_authenticated %}

        <div class="yellow-header">
            <p class="text-center text-white header-text">Éditer mes informations</p>
            <div class="separated-div-wrapper">
                <div class="separators header"></div>
                <div class="separators header center-white"></div>
                <div class="separators header"></div>
            </div>
        </div>

        <div class="container py-2">
            <div id="userForm">
                <div class="card card-body">
                    Les champs suivis d'une astérisque sont obligatoires. <br>
                    <form method="POST" enctype='multipart/form-data'>
                        {#                    TODO: Create a new form for update user info#}
                        {% csrf_token %}
                        {% for field in user_update_form %}
                            <p>
                                {{ field | as_crispy_field }}
                                {% for error in field.errors %}
                                    <small class="errors">{{ error }}</small>
                                {% endfor %}
                            </p>
                        {% endfor %}
                        <button class="btn btn-primary" type="submit" name="user_registration">Mettre à jour</button>
                    </form>
                </div>
            </div>
        </div>

    {% else %}


        <div class="yellow-header">
            <p class="text-center text-white header-text">Vous n'êtes pas connecté!</p>
            <div class="separated-div-wrapper">
                <div class="separators header"></div>
                <div class="separators header center-white"></div>
                <div class="separators header"></div>
            </div>
        </div>
    {% endif %}
{% endblock content %}

{% block myjssheet %}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#id_birthday").datepicker();
        });
    </script>
{% endblock myjssheet %}